version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Build + SBOM
          command: ./gradlew build cyclonedxBom

      - run:
          name: Trivy scan
          command: |
            trivy sbom \
              --scanners license \
              --severity CRITICAL \
              --exit-code 1 \
              build/reports/application.cdx.json

workflows:
  build-security:
    jobs:
      - build